Repository shriyaMadan/Youtube-Dashboard, pull requests merged in 2020-12, with the labels that each got.

#32 Secondary
  .gitignore
  app.js
  config.js
  controllers/controls.js
  package-lock.json
  package.json
  routes/index.js
  views/index.ejs
  views/statPub.ejs
Labels: DWOC, Level-4

#36 base ui-css-animation
  public/stylesheets/index.css
  views/statPub.ejs
Labels: DWOC, Level-2

#35 search suggestion feature added
  package-lock.json
  views/statPub.ejs
Labels: DWOC, Level-3

#38 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: DWOC, Level-2
