Repository shriyaMadan/Youtube-Dashboard, pull requests merged in 2021-01, with the labels that each got.

#34 Adding contributing file
  Contributing File Images/add.PNG
  Contributing File Images/cd.PNG
  Contributing File Images/checkout.PNG
  Contributing File Images/clone.png
  Contributing File Images/commit.PNG
  Contributing File Images/push.PNG
  Contributing File Images/remote.PNG
  Contributing File Images/upstream.PNG
  Contributing File Images/úpstrea.PNG
  Contributing.md
Labels: DWOC, Level-2

#52 added navbar
  client/.eslintcache
  client/package-lock.json
  client/package.json
  client/public/nav-logo.png
  client/src/App.js
  client/src/components/card/Card.jsx
  client/src/components/card/card.css
  client/src/components/navbar/Navbar.jsx
  client/src/components/navbar/navbar.css
  client/src/context/AuthContext.js
  client/src/index.css
  client/src/pages/landing/LandingPage.jsx
  client/src/pages/landing/landingpage.css
Labels: DWOC, Level-4

#59 added the contributing file
  CONTRIBUTING.md
  README.md
Labels: DWOC

#66 Integrate Welcome Bot
  .github/config.yml
Labels: DWOC, Level-2

#69 fix(index): revamped index.ejs
  public/stylesheets/landing.css
  views/index.ejs
Labels: DWOC, Level-3

#71 Add Template for Issues
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/ISSUE_TEMPLATE/proposal.md
Labels: DWOC, Level-2

#75 Updated issue template
  .github/ISSUE_TEMPLATE/---bug-report-.md
  .github/ISSUE_TEMPLATE/---documentation.md
  .github/ISSUE_TEMPLATE/---feature-request.md
  .github/ISSUE_TEMPLATE/-proposal.md
Labels: DWOC, Level-1

#76 Website Logo
  public/images/logo.png
Labels: DWOC, Level-2

#88 improve readme & add links to discord & wiki
  README.md
Labels: DWOC, Level-3

#95 Dashboard-design
  designs/design.md
  designs/files/dashboard-design-SuNiL-Chau.fig
Labels: DWOC, Level-3
